### ISSUE TITLE
npm run build fails to minify

### ISSUE THREAD

**Issue by vitthalr** [ratson/react-intl-redux#41] opened 2017-09-18 13:29 UTC
I'm using server-side rendering with Create React App.

When I try to create a build, it shows following error, please help!

```
BSBLRLT226:trunk vitthalroonwal$ npm run build

> BlueStone-React-PWA-App@0.1.0 build /Users/vitthalroonwal/bluestone/dev/bluestone.react/trunk
> npm run build-css && react-scripts build


> BlueStone-React-PWA-App@0.1.0 build-css /Users/vitthalroonwal/bluestone/dev/bluestone.react/trunk
> node-sass-chokidar src/assets/ -o src/assets/

Rendering Complete, saving .css file...
Wrote CSS to /Users/vitthalroonwal/bluestone/dev/bluestone.react/trunk/src/assets/scss/app.css
Wrote 1 CSS files to /Users/vitthalroonwal/bluestone/dev/bluestone.react/trunk/src/assets/
Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file: 

 	./node_modules/redux-lang/src/actions.js:3 

Read more here: http://bit.ly/2tRViJ9


npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! BlueStone-React-PWA-App@0.1.0 build: `npm run build-css && react-scripts build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the BlueStone-React-PWA-App@0.1.0 build script 'npm run build-css && react-scripts build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the BlueStone-React-PWA-App package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build-css && react-scripts build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs BlueStone-React-PWA-App
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls BlueStone-React-PWA-App
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/vitthalroonwal/bluestone/dev/bluestone.react/trunk/npm-debug.log
```

Thanks in Advance, hoping to get a solution asap.

**Comment by ratson** [comment] 2017-10-08 15:44
@vitthalr You log is showing the error is from `redux-lang`.

Closing it now, feel free to re-open if you confirmed it is caused by `react-intl-redux`.

**Closed by ratson** 2017-10-08 15:44 UTC

**Comment by lgoldfish** [comment] 2017-12-17 12:46
Failed to minify the code from this file:    Read more here: http://bit.ly/2tRViJ9
